# -*- coding: utf-8 -*-
"""code.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NsFG7xnWsy3d0bhz7Jp-56pKL_M3tN7l
"""

from datetime import datetime, timedelta

MILEAGE_THRESHOLD = 10000
TIME_THRESHOLD_DAYS = 365

last_service_date_str = input("Enter last service date (YYYY-MM-DD): ")
current_mileage = int(input("Enter current mileage (in km): "))
last_service_mileage = int(input("Enter mileage at last service (in km): "))

last_service_date = datetime.strptime(last_service_date_str, "%Y-%m-%d")
today = datetime.today()

days_since_service = (today - last_service_date).days
km_since_service = current_mileage - last_service_mileage

service_due = False
reasons = []

if days_since_service >= TIME_THRESHOLD_DAYS:
    service_due = True
    reasons.append(f"Time: {days_since_service} days since last service")

if km_since_service >= MILEAGE_THRESHOLD:
    service_due = True
    reasons.append(f"Mileage: {km_since_service} km since last service")

print("\n===== Service Reminder =====")
if service_due:
    print("Service is DUE!")
    for r in reasons:
        print("-", r)
else:
    print("Service is NOT yet due.")
    print(f"Days since last service: {days_since_service}")
    print(f"Kilometers since last service: {km_since_service}")